name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    permissions:
      contents: write  
      id-token: write   

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - id: install-deps
        name: Install dependencies
        run: |
          bun install

      - id: test
        name: Run tests
        run: |
          bun test

      - id: create_tag
        name: Create Tag
        run: |
          # Configure git user for tagging
          git config --global user.email "yassine@rais.me"
          git config --global user.name "Yassine Rais"
          
          # Retrieve version from package.json using bun
          VERSION=$(bun --print "require('./package.json').version")
          echo "Version: $VERSION"

          # Try to get the latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "none")
          echo "Latest Tag: $LATEST_TAG"

          # If no tags are found, LATEST_TAG will be 'none'
          if [ "$LATEST_TAG" != "v$VERSION" ]; then
            echo "New version detected. Creating a new tag."
          
            # Create a new git tag using the version
            git tag "v$VERSION"
            
            # Push the tag to the remote repository
            git push origin "v$VERSION"
          else
            echo "No version change detected. Skipping tag creation."
          fi
